Indent

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -18,25 +18,25 @@ jobs:
       - name: Create a package called @${{ github.repository }}
         run: |
           echo '{
-  "name": "@jcansdale-test/npm-license-test",
-  "version": "1.0.0",
-  "description": "Example publishing an npm package.",
-  "main": "index.js",
-  "scripts": {
-    "test": "echo \"Error: no test specified\" && exit 1"
-  },
-  "repository": {
-    "type": "git",
-    "url": "git+https://github.com/jcansdale-test/npm-license-test.git"
-  },
-  "keywords": [],
-  "author": "",
-  "license": "ISC",
-  "bugs": {
-    "url": "https://github.com/jcansdale-test/npm-license-test/issues"
-  },
-  "homepage": "https://github.com/jcansdale-test/npm-license-test#readme"
-}' > package.json
+            "name": "@jcansdale-test/npm-license-test",
+            "version": "1.0.0",
+            "description": "Example publishing an npm package.",
+            "main": "index.js",
+            "scripts": {
+              "test": "echo \"Error: no test specified\" && exit 1"
+            },
+            "repository": {
+              "type": "git",
+              "url": "git+https://github.com/jcansdale-test/npm-license-test.git"
+            },
+            "keywords": [],
+            "author": "",
+            "license": "ISC",
+            "bugs": {
+              "url": "https://github.com/jcansdale-test/npm-license-test/issues"
+            },
+            "homepage": "https://github.com/jcansdale-test/npm-license-test#readme"
+          }' > package.json
           cat package.json
 
       - name: Add index.js to package
